sudo: false
dist: trusty
language: node_js
env:
  global:
    - GET_ENV_VAR=./_scripts/get_env.sh
    - GOPATH="${HOME}/.go_workspace"
    - TRAVIS_NODE_VERSION="8.16.0"
    - CF_APP=mx-developer
    - CF_API=https://api.run.pivotal.io
    - CF_USERNAME=jelte.lagendijk@mendix.com
    - CF_ORGANIZATION=mendix-rnd.com
    - CF_SPACE=community
    - CF_CLI_VERSION=6.22.2
    - secure: EcQR5m9oGullB6BK0BzsPIXxCKr+2/lHvWrhTyz9eZfHclq+Ddd0+ZhZ5wV+H26/H2omTF2DNPFsabOv51bIQgDpR5wF9aSKgnW9e8CbB8YKjNL/HaDiexfteSJQ0/xRyvnm+8ZMIVJXic1jjLBAtKeXnJ2Zs4pUweRrdMioz7EMZr+GJGmzeAHAkxVdh/Z2uyK+9SBo0HAW7HpIAMxOQI9aZyBMX6tZTnN/hfKMGKBevUwB1DMjKaJhjYt/s748clQM/jiyAag7VNkjxXSu+hNApuaUqRa3eAFEC6jlbzc9+Pg0Vjf3DMvm3PSZAnPXM2qcbqulgvP/8193qqJ4M58h5OzWCIUIif/mFoPwMIwT4gQlouK6FnjmbCBi0YXEhZKP+RKtjx425DpBLeNrmPt04zEggU7F9tOpFK6uWROZ7JvGQdssdEoW7j6nqmS2vDhA8ACKwoVv3r4aGQ2O1ik6x7musuTaFvfiQ3qFsHZbIAZJKNJTLnuJIS2LQxUj2rUI8zbatAm8ViRN8XKa9L4KWYCSXaw0Yi29aE8ur5zhozmStKXtlIMbUmwT36eRwW9xyqxbDvACU5dmL++kNu7mY2YtMHdpMnNb25Viq9Ljj/l99XjbUioRh25Aj1lUGcvK57W+64Dm7xNuy14kidBiTiZcsOjL/04ASGOyd9U=
install:
  - rm -rf build
  - yarn
before_deploy:
  - export PATH=$HOME:$PATH
  - travis_retry curl -L -o $HOME/cf.tgz "https://cli.run.pivotal.io/stable?release=linux64-binary&version=$CF_CLI_VERSION"
  - tar xzvf $HOME/cf.tgz -C $HOME
  - chmod +x $HOME/cf
  - mv $HOME/cf $HOME/bin/cf
  - cp ./_scripts/autopilot-linux $HOME/
  - chmod a+x $HOME/autopilot-linux
  - ./_scripts/before_deploy.sh
script:
  - yarn build:prod
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - master
    - development
deploy:
  - provider: script
    script:
      - ./_scripts/deploy.sh
    skip_cleanup: true
    on:
      branch:
        - master
        - development
